=== CNR-Engineering/Crue10_tools/crue10/data/xsd/1.3/CrueConfigMetier-1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="http://www.fudaa.fr/xsd/crue" xmlns="http://www.fudaa.fr/xsd/crue">

	<xs:annotation>
		<!-- La Version et la Release doivent être mises à jour à chaque modification de cette xsd -->
		<xs:documentation xml:lang="fr">
			Version 1.3 Release 1
			Fichier de configuration métier, commun à Fudaa-Crue et Crue10
		</xs:documentation>
	</xs:annotation>
	
	<xs:simpleType name="TypeForAttributeConfigNom">
		<xs:restriction base="xs:ID"/>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeCtrlLoi">
		<xs:restriction base="TypeForAttributeConfigNom">
			<xs:pattern value="Tco_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeExtraLoi">
		<xs:restriction base="TypeForAttributeConfigNom">
			<xs:pattern value="Tex_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeNumerique">
		<xs:restriction base="TypeForAttributeConfigNom">
			<xs:pattern value="Tnu_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeEnum">
		<xs:restriction base="TypeForAttributeConfigNom">
			<xs:pattern value="Ten_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeNature">
		<xs:restriction base="TypeForAttributeConfigNom">
			<xs:pattern value="Nat_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomRef">
		<xs:restriction base="xs:IDREF" />
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeCtrlLoiRef">
		<xs:restriction base="TypeForAttributeConfigNomRef">
			<xs:pattern value="Tco_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeExtraLoiRef">
		<xs:restriction base="TypeForAttributeConfigNomRef">
			<xs:pattern value="Tex_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeNumeriqueRef">
		<xs:restriction base="TypeForAttributeConfigNomRef">
			<xs:pattern value="Tnu_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeEnumRef">
		<xs:restriction base="TypeForAttributeConfigNomRef">
			<xs:pattern value="Ten_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeForAttributeConfigNomTypeNatureRef">
		<xs:restriction base="TypeForAttributeConfigNomRef">
			<xs:pattern value="Nat_.*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeInfini">
	    <xs:restriction base="xs:string">
	    	<xs:enumeration value="+Infini"/>
	    	<xs:enumeration value="-Infini"/>
	    </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeDoubleInfini">
		<xs:union memberTypes="xs:double xs:dateTime TypeInfini"/>
	</xs:simpleType>

	<xs:simpleType name="TypeNull">
	    <xs:restriction base="xs:string">
	    	<xs:length value="0"/>
	    </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeToken32">
		<xs:restriction base="xs:token">
			<xs:minLength value="1" />
			<xs:maxLength value="32" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="TypeEnumValeur">
		<xs:union memberTypes="TypeToken32"/>
	</xs:simpleType>
	
	<xs:simpleType name="TypeEnumValeurDefaut">
		<xs:union memberTypes="TypeNull TypeEnumValeur"/>
	</xs:simpleType>
	
	<xs:simpleType name="TypeValeur">
		<xs:union memberTypes="TypeDoubleInfini"/>
	</xs:simpleType>
	
	<xs:simpleType name="TypeValeurDefaut">
		<xs:union memberTypes="TypeNull TypeValeur"/>
	</xs:simpleType>
	
	<xs:simpleType name="TypeDoublePositif">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0.0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TypeVecteur">
		<xs:annotation>
			<xs:documentation>
				Permet de spécifier des valeurs du style vecteur. Exemple 0.00 1.00 2.00 3.00 ...
			</xs:documentation>
		</xs:annotation>
		<xs:list itemType="xs:double" />
	</xs:simpleType>

	<xs:complexType name="TypeValeurStrictable">
		<xs:simpleContent>
			<xs:extension base="TypeValeur">
				<xs:attribute name="Strict" type="xs:boolean" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:element name="ItemTypeControleLoi">
		<xs:complexType>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNomTypeCtrlLoi" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="TypeControleLois">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemTypeControleLoi" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ItemTypeExtrapolLoi">
		<xs:complexType>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNom" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="TypeExtrapolLois">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemTypeExtrapolLoi" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ItemTypeNumerique">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Infini" type="xs:double"/>
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNomTypeNumerique" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="TypeNumeriques">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemTypeNumerique" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ItemTypeEnum">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ItemEnum" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="TypeToken32">
								<xs:attribute name="Id" type="xs:nonNegativeInteger" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNomTypeEnum" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="TypeEnums">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemTypeEnum" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ItemNature">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TypeNumerique">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeNumeriqueRef" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="EpsilonComparaison" type="TypeDoublePositif"/>
				<xs:element name="EpsilonComparaisonFC" type="TypeDoublePositif"/>
				<xs:element name="EpsilonPresentation" type="TypeDoublePositif"/>
				<xs:element name="Unite" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNom" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Natures">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemNature" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ItemConstante">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element name="TypeEnum">
						<xs:complexType>
							<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeEnumRef" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="EnumValeur" type="TypeEnumValeur"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element name="Nature">
						<xs:complexType>
							<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeNatureRef" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="Valeur" type="TypeValeur"/>
					<xs:element name="MinValidite" type="TypeValeurStrictable"/>
					<xs:element name="MaxValidite" type="TypeValeurStrictable"/>
					<xs:element name="MinNormalite" type="TypeValeurStrictable"/>
					<xs:element name="MaxNormalite" type="TypeValeurStrictable"/>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNom" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ItemConstanteVecteur">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Nature">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeNatureRef" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ValeurVecteur" type="TypeVecteur"/>
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNom" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Constantes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemConstante" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ItemConstanteVecteur" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ItemVariable">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element name="TypeEnum">
						<xs:complexType>
							<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeEnumRef" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="EnumValeurDefaut" type="TypeEnumValeurDefaut"/>
				</xs:sequence>
				<xs:sequence>
					<xs:element name="Nature">
						<xs:complexType>
							<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeNatureRef" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="ValeurDefaut" type="TypeValeurDefaut"/>
					<xs:element name="MinValidite" type="TypeValeurStrictable"/>
					<xs:element name="MaxValidite" type="TypeValeurStrictable"/>
					<xs:element name="MinNormalite" type="TypeValeurStrictable"/>
					<xs:element name="MaxNormalite" type="TypeValeurStrictable"/>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNom" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Variables">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemVariable" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="ItemConfigLoi">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Commentaire" type="xs:string" minOccurs="0"/>
				<xs:element name="TypeControleLoi">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeCtrlLoiRef" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ExtrapolInf">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeExtraLoiRef" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ExtrapolSup">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomTypeExtraLoiRef" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="VarAbscisse">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomRef" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="VarOrdonnee">
					<xs:complexType>
						<xs:attribute name="NomRef" type="TypeForAttributeConfigNomRef" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeConfigNom" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="ConfigLois">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ItemConfigLoi" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="CrueConfigMetier">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TypeControleLois"/>
				<xs:element ref="TypeExtrapolLois"/>
				<xs:element ref="TypeNumeriques"/>
				<xs:element ref="TypeEnums"/>
				<xs:element ref="Natures"/>
				<xs:element ref="Constantes"/>
				<xs:element ref="Variables"/>
				<xs:element ref="ConfigLois"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CNR-Engineering/Crue10_tools/crue10/data/CrueConfigMetier.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Ce fichier xml est à mettre dans le répertoire de l'exécutable Crue10 -->
<CrueConfigMetier xmlns="http://www.fudaa.fr/xsd/crue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fudaa.fr/xsd/crue http://www.fudaa.fr/xsd/crue/CrueConfigMetier-1.3.xsd">
  <!-- Toutes les balises sont obligatoires, ainsi que leurs attributs. Sauf 
    précision contraire, les balises ne peuvent pas être vides. -->

  <!-- ATTENTION ! Note de maintenance des fichiers CCM :
    Pour maintenir en cohérence les fichiers CCM de toutes les grammaire, il faut :
    - identifier par un commentaire contenant le mot "grammaire" tous les endroits où les changements de grammaire ont un impact,
    - tenir à jour le fichier CCM de la grammaire la plus récente, en fonction des évolutions de grammaire,
      en laissant en commentaire les parties nécessaires aux anciennes grammaires,
    - tenir à jour le fichier CCM de la grammaire la plus récente, en fonction des évolutions fonctionnelles (changements de valeurs, ajout de variables...),
      en n'oubliant pas de modifier aussi les variables correspondantes des grammaires précédentes, 
    - à partir du fichier CCM de la grammaire la plus récente, regénérer les fichiers CCM des grammaires précédentes en commentant/décommentant les lignes ad hoc,
    - en conséquence, AUCUN COMMENTAIRE autre que technique n'est autorisé dans ce fichier, parce qu'il peut rendre inopérant le mécanisme ci-dessus,
    - les commentaires fonctionnels sont hébergés dans le dictionnaire de données.
  -->

  <!--||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||					
			ATTENTION : Pour toute modification du fichier, exécuter dev_genererResIndus.bat à la racine de la solution dans le répertoire "src"
		  ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||-->

  <!-- Type de controle qui sera effectué sur la variation de la loi, sachant 
    que l'ordre de rangement des points donne toujours l'ordre de progression -->
  <TypeControleLois>
    <ItemTypeControleLoi Nom="Tco_Aucun" />
    <!-- Aucun contrôle sur les variations des abscisses et des ordonnées -->
    <ItemTypeControleLoi Nom="Tco_AbsCrt" />
    <!-- Les abscisses doivent être croissantes mais pas forcément strictement, 
      donc 2 points consécutifs peuvent avoir la même abscisse -->
    <ItemTypeControleLoi Nom="Tco_AbsCrtStrict" />
    <!-- Les abscisses doivent être strictement croissantes -->
  </TypeControleLois>
  <!-- Types d'extrapolation, appliqués à une extrémité d'une loi -->
  <TypeExtrapolLois>
    <ItemTypeExtrapolLoi Nom="Tex_Aucun" />
    <!-- Aucune extrapolation possible -->
    <ItemTypeExtrapolLoi Nom="Tex_OrdCst" />
    <!-- Extrapolation à valeur de l'ordonnée constante -->
    <ItemTypeExtrapolLoi Nom="Tex_OrdInterpolLineaire" />
    <!-- Extrapolation par interpolation linéaire de l'ordonnée -->
  </TypeExtrapolLois>
  <!-- Types numériques de stockage à affecter à chaque Nature de Variable -->
  <!-- Dans les fichiers binaires, 
    une variable de type Tnu_Entier est stockée dans un entier signé 32 bits
    une variable de type Tnu_Reel est stockée dans un reel IEEE 64 bits,
    une variable de type Enum est stockée dans une chaine de 32 car. -->
  <TypeNumeriques>
    <ItemTypeNumerique Nom="Tnu_Entier">
      <Infini>2000000000</Infini>
    </ItemTypeNumerique>
    <ItemTypeNumerique Nom="Tnu_Reel">
      <Infini>1.0E30</Infini>
    </ItemTypeNumerique>
  </TypeNumeriques>

  <TypeEnums>
    <!-- En grammaire v1.1.1, ItemEnum n'a pas d'attribut Id
         En grammaire v1.2,   ItemEnum a un attribut Id
    <ItemTypeEnum Nom="Ten_ClicheOrigine">
      <ItemEnum Id="0">CalculPseudoPermanent</ItemEnum>
      <ItemEnum Id="1">CalculTransitoire</ItemEnum>
      <ItemEnum Id="2">Initialisation</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_ClicheQualite">
      <ItemEnum Id="0">Normale</ItemEnum>
      <ItemEnum Id="1">Erreur</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_Etiquette">
      <ItemEnum>Et_AxeHyd</ItemEnum>
      <ItemEnum>Et_LimLit</ItemEnum>
      <ItemEnum>Et_Thalweg</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_FormulePdc">
      <ItemEnum>DIVERGENT</ItemEnum>
      <ItemEnum>BORDA</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_LitNomme">
      <ItemEnum>Lt_StoD</ItemEnum>
      <ItemEnum>Lt_MajD</ItemEnum>
      <ItemEnum>Lt_Mineur</ItemEnum>
      <ItemEnum>Lt_MajG</ItemEnum>
      <ItemEnum>Lt_StoG</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_MethodeInterpol">
      <ItemEnum>ZIMP_AUX_SECTIONS</ItemEnum>
      <ItemEnum>LINEAIRE</ItemEnum>
      <ItemEnum>SAINT_VENANT</ItemEnum>
      <ItemEnum>BAIGNOIRE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_PosBordure">
      <ItemEnum>PAS_BORDURE</ItemEnum>
      <ItemEnum>BORDURE_DROITE</ItemEnum>
      <ItemEnum>BORDURE_GAUCHE</ItemEnum>
      <ItemEnum>BORDURE_2_COTES</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_PosSection">
      <ItemEnum>AMONT</ItemEnum>
      <ItemEnum>INTERNE</ItemEnum>
      <ItemEnum>AVAL</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_RegimeBarrage">
      <ItemEnum>MANOEUVRANT</ItemEnum>
      <ItemEnum>EFFACE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_RegimeOrifice">
      <ItemEnum>HORS_EAU</ItemEnum>
      <ItemEnum>NSU_DEN</ItemEnum>
      <ItemEnum>NSU_NOY</ItemEnum>
      <ItemEnum>SUB_DEN</ItemEnum>
      <ItemEnum>SUB_NOY</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_RegimeSeuil">
      <ItemEnum>HORS_EAU</ItemEnum>
      <ItemEnum>NSU_DEN</ItemEnum>
      <ItemEnum>NSU_NOY</ItemEnum>
      <ItemEnum>MIXTE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_SensOrifice">
      <ItemEnum>BIDIRECT</ItemEnum>
      <ItemEnum>DIRECT</ItemEnum>
      <ItemEnum>INDIRECT</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_SensOuv">
      <ItemEnum>OUV_VERS_HAUT</ItemEnum>
      <ItemEnum>OUV_VERS_BAS</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_Severite">
      <ItemEnum>FATAL</ItemEnum>
      <ItemEnum>ERRBLK</ItemEnum>
      <ItemEnum>ERRNBLK</ItemEnum>
      <ItemEnum>WARN</ItemEnum>
      <ItemEnum>INFO</ItemEnum>
      <ItemEnum>FCT1</ItemEnum>
      <ItemEnum>FCT2</ItemEnum>
      <ItemEnum>FCT3</ItemEnum>
      <ItemEnum>DEBUG1</ItemEnum>
      <ItemEnum>DEBUG2</ItemEnum>
      <ItemEnum>DEBUG3</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_TypeLit">
      <ItemEnum>MINEUR</ItemEnum>
      <ItemEnum>MAJEUR</ItemEnum>
      <ItemEnum>STOCKAGE</ItemEnum>
    </ItemTypeEnum>
    -->
    <!-- En grammaire v1.1.1, ItemEnum n'a pas d'attribut Id
         En grammaire v1.2,   ItemEnum a un attribut Id
    -->
    <ItemTypeEnum Nom="Ten_ClicheOrigine">
      <ItemEnum Id="0">CalculPseudoPermanent</ItemEnum>
      <ItemEnum Id="1">CalculTransitoire</ItemEnum>
      <ItemEnum Id="2">Initialisation</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_ClicheQualite">
      <ItemEnum Id="0">Normale</ItemEnum>
      <ItemEnum Id="1">Erreur</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_Etiquette">
      <ItemEnum Id="0">Et_AxeHyd</ItemEnum>
      <ItemEnum Id="1">Et_LimLit</ItemEnum>
      <ItemEnum Id="2">Et_Thalweg</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_FormulePdc">
      <ItemEnum Id="0">DIVERGENT</ItemEnum>
      <ItemEnum Id="1">BORDA</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_LitNomme">
      <ItemEnum Id="0">Lt_StoD</ItemEnum>
      <ItemEnum Id="1">Lt_MajD</ItemEnum>
      <ItemEnum Id="2">Lt_Mineur</ItemEnum>
      <ItemEnum Id="3">Lt_MajG</ItemEnum>
      <ItemEnum Id="4">Lt_StoG</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_MethodeInterpol">
      <ItemEnum Id="0">ZIMP_AUX_SECTIONS</ItemEnum>
      <ItemEnum Id="1">LINEAIRE</ItemEnum>
      <ItemEnum Id="2">SAINT_VENANT</ItemEnum>
      <ItemEnum Id="3">BAIGNOIRE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_Mode">
      <ItemEnum Id="-1">DECRUE</ItemEnum>
      <ItemEnum Id="1">MONTEE CRUE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_PosBordure">
      <ItemEnum Id="0">PAS_BORDURE</ItemEnum>
      <ItemEnum Id="1">BORDURE_DROITE</ItemEnum>
      <ItemEnum Id="2">BORDURE_GAUCHE</ItemEnum>
      <ItemEnum Id="3">BORDURE_2_COTES</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_PosSection">
      <ItemEnum Id="0">AMONT</ItemEnum>
      <ItemEnum Id="1">INTERNE</ItemEnum>
      <ItemEnum Id="2">AVAL</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_RegimeBarrage">
      <ItemEnum Id="0">MANOEUVRANT</ItemEnum>
      <ItemEnum Id="1">NOYE</ItemEnum>
      <ItemEnum Id="2">DENOYE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_RegimeOrifice">
      <ItemEnum Id="0">HORS_EAU</ItemEnum>
      <ItemEnum Id="1">NSU_DEN</ItemEnum>
      <ItemEnum Id="2">NSU_NOY</ItemEnum>
      <ItemEnum Id="3">SUB_DEN</ItemEnum>
      <ItemEnum Id="4">SUB_NOY</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_RegimeSeuil">
      <ItemEnum Id="0">HORS_EAU</ItemEnum>
      <ItemEnum Id="1">NSU_DEN</ItemEnum>
      <ItemEnum Id="2">NSU_NOY</ItemEnum>
      <ItemEnum Id="3">MIXTE</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_SensOrifice">
      <ItemEnum Id="0">BIDIRECT</ItemEnum>
      <ItemEnum Id="1">DIRECT</ItemEnum>
      <ItemEnum Id="2">INDIRECT</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_SensOuv">
      <ItemEnum Id="0">OUV_VERS_HAUT</ItemEnum>
      <ItemEnum Id="1">OUV_VERS_BAS</ItemEnum>
    </ItemTypeEnum>
    <ItemTypeEnum Nom="Ten_Severite">
