=== CNR-Engineering/Crue10_tools/crue10/data/xsd/1.3/etu-1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified"
	targetNamespace="http://www.fudaa.fr/xsd/crue" xmlns="http://www.fudaa.fr/xsd/crue">

	<xs:annotation>
		<!-- La Version et la Release doivent être mises à jour à chaque modification de cette xsd -->
		<xs:documentation xml:lang="fr">
			Version 1.3 Release 2
			Ce schema est utilise pour valider
			le fichier ETU
		</xs:documentation>
	</xs:annotation>

	<xs:include schemaLocation="nomRef-fichierConcat-1.3.xsd" />
	<xs:include schemaLocation="frag-common-1.3.xsd" />

	<xs:element name="AuteurCreation" type="xs:string" />
	<xs:element name="DateCreation" type="xs:dateTime" />
	<xs:element name="DateDerniereModif" type="xs:dateTime" />
	<xs:element name="AuteurDerniereModif" type="xs:string" />
	<xs:element name="Rapports" type="xs:string" />
	<xs:element name="Type" type="TypeScenarioType" />

	<xs:simpleType name="TypeScenarioType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Crue10" />
			<xs:enumeration value="Crue9" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="Repertoire">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="path" type="xs:string" />
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNom" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Repertoires">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Repertoire" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- FichEtudes -->

	<xs:element name="FichEtude">
		<xs:complexType>
			<xs:attribute name="Nom" type="TypeForAttributeNom" use="required" />
			<xs:attribute name="Chemin" type="xs:string" use="required" />
			<xs:attribute name="Type" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TypeFichEtudes">
		<xs:sequence>
			<xs:element ref="FichEtude" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!--  SousModeles -->

	<xs:element name="SousModeles">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SousModele" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="SousModele">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Type" />
				<xs:element name="IsActive" type="xs:boolean" />
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />
				<xs:element name="SousModele-FichEtudes" type="TypeListeReferencesFichierSousModele" />
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNomSousModele"
				use="required" />
		</xs:complexType>
	</xs:element>

	<!--  Modeles -->
	
	<xs:element name="Modele">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" fixed="Crue10" />
				<xs:element name="IsActive" type="xs:boolean" />
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />
				<xs:element name="Modele-FichEtudes" type="TypeListeReferencesFichierModele" />
				<xs:element name="Modele-SousModeles" minOccurs="0"
					type="TypeListeReferencesSousModele" />
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNomModele"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="ModeleV9">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" fixed="Crue9" />
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />
				<xs:element name="ModeleV9-FichEtudes" type="TypeListeReferencesFichierModeleV9" />
				<!--
					xs:element name="SousModeles" minOccurs="0"
					type="TypeListeReferencesSousModele" /
				-->
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNomModele"
				use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="Modeles">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Modele" />
				<xs:element ref="ModeleV9" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<!--  Scenarios -->
	
	<xs:element name="Scenarios">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="Scenario" />
				<xs:element ref="ScenarioV9" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="Scenario">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" fixed="Crue10" />
				<xs:element name="IsActive" type="xs:boolean" />
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />

				<!-- xs:element ref="DateDerniereModif" /-->
				<xs:element name="Scenario-FichEtudes" type="TypeListeReferencesFichierScenario" minOccurs="0" />
				<xs:element name="Scenario-Modeles" type="TypeListeReferencesModele" />
				<xs:element name="Scenario-ScenarioV9" type="TypeNomRefLocal" minOccurs="0" />
				<xs:element ref="Runs" minOccurs="0" />
				<xs:element name="RunCourant" type="TypeNomRefLocal" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNomScenario" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="ScenarioV9">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Type" fixed="Crue9" />
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />
				<!-- xs:element ref="DateDerniereModif" /-->
				<xs:element name="Scenario-ModeleV9" type="TypeNomRefLocal" />
				<xs:element ref="RunV9s" minOccurs="0" />
				<xs:element name="RunCourant" type="TypeNomRefLocal"
					minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNomScenario"
				use="required" />
		</xs:complexType>
	</xs:element>

	<!--  RUNS -->
	
	<xs:element name="Runs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Run" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="RunV9s">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RunV9" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Run">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />
      </xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNom" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="RunV9">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Commentaire" />
			</xs:sequence>
			<xs:attribute name="Nom" type="TypeForAttributeNom" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- Liste des fichiers acceptés au niveau SousModele -->
	<xs:complexType name="TypeListeReferencesFichierSousModele">
		<xs:sequence>
			<xs:element ref="DRSO" />
			<xs:element ref="DCSP" />
			<xs:element ref="DPTG" />
			<xs:element ref="DFRT" />
		</xs:sequence>
	</xs:complexType>

	<!-- Liste des fichiers acceptés au niveau Modele -->
	<xs:complexType name="TypeListeReferencesFichierModele">
		<xs:sequence>
			<xs:element ref="OPTR" />
			<xs:element ref="OPTG" />
			<xs:element ref="OPTI" />
			<xs:element ref="PNUM" />
			<xs:element ref="DPTI" />
			<xs:element ref="DREG" minOccurs="0" /> <!-- Ajout MEC-Crue10-->
		</xs:sequence>
	</xs:complexType>

	<!-- Liste des fichiers acceptés au niveau ModeleV9 -->
	<xs:complexType name="TypeListeReferencesFichierModeleV9">
		<xs:sequence>
			<xs:element ref="DC" />
			<xs:element ref="DH" />
		</xs:sequence>
	</xs:complexType>

	<!-- Liste des fichiers acceptés au niveau scenario -->
	<xs:complexType name="TypeListeReferencesFichierScenario">
		<xs:sequence>
			<xs:element ref="OCAL" />
			<xs:element ref="ORES" />
			<xs:element ref="PCAL" />
			<xs:element ref="DCLM" />
			<xs:element ref="DLHY" />
		</xs:sequence>
	</xs:complexType>


	<!-- Definition des références de fichiers -->

	<xs:simpleType name="TypeXmlIdRef">
		<xs:restriction base="xs:IDREF">
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="OCAL">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.ocal\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="ORES">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.ores\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="PCAL">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.pcal\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DCLM">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dclm\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DLHY">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dlhy\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="OPTR">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.optr\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="OPTG">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.optg\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="OPTI">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.opti\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="PNUM">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.pnum\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DPTI">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dpti\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DREG"> <!-- Ajout MEC-Crue10-->
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dreg\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DC">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dc"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DH">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dh"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DRSO">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.drso\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DCSP">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dcsp\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DPTG">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dptg\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="DFRT">
		<xs:complexType>
			<xs:attribute name="NomRef" use="required">
				<xs:simpleType>
					<xs:restriction base="TypeXmlIdRef">
						<xs:pattern value=".*[^\s].*\.dfrt\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<!-- Les résultats -->
	
	<xs:element name="RCAL">
		<xs:complexType>
			<xs:attribute name="Nom" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:pattern value=".*[^\s].*\.rcal"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="RPTR">
		<xs:complexType>
			<xs:attribute name="Nom" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:pattern value=".*[^\s].*\.rptr"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="RPTG">
		<xs:complexType>
			<xs:attribute name="Nom" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:pattern value=".*[^\s].*\.rptg"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="RPTI">
		<xs:complexType>
			<xs:attribute name="Nom" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:pattern value=".*[^\s].*\.rpti\.xml"></xs:pattern>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="TypeListeReferencesSousModele">
		<xs:sequence>
			<xs:element name="Modele-SousModele" type="TypeNomRefLocal"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="TypeListeReferencesModele">
		<xs:sequence>
			<xs:element name="Scenario-Modele" type="TypeNomRefLocal" />
		</xs:sequence>
	</xs:complexType>

	<!--  FICHIER ETU -->
	
	<xs:element name="ETU">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Commentaire" />
				<xs:element ref="AuteurCreation" />
				<xs:element ref="DateCreation" />
				<xs:element ref="AuteurDerniereModif" />
				<xs:element ref="DateDerniereModif" />
				<xs:element name="ScenarioCourant" type="TypeNomRefLocal" minOccurs="0" />
				<xs:element ref="Repertoires" />
				<xs:element name="FichEtudes" type="TypeFichEtudes" />
				<xs:element ref="SousModeles" />
				<xs:element ref="Modeles" />
				<xs:element ref="Rapports" minOccurs="0" />
				<xs:element ref="Scenarios" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CNR-Engineering/Crue10_tools/crue10/tests/data/in/1.3/Etu3-6I_run/Runs/Sc_M3-6I_c10/R2023-04-21-15h39m47s/Etu3-6.etu.xml
<?xml version="1.0" encoding="UTF-8"?>
<ETU xmlns="http://www.fudaa.fr/xsd/crue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fudaa.fr/xsd/crue http://www.fudaa.fr/xsd/crue/etu-1.3.xsd">
  <Commentaire>Etu3-6 : étude basée sur Etu3-0</Commentaire>
  <AuteurCreation>BALAYN_P</AuteurCreation>
  <DateCreation>2012-05-30T12:00:00.000</DateCreation>
  <AuteurDerniereModif>DURON</AuteurDerniereModif>
  <DateDerniereModif>2023-04-21T15:39:47.976</DateDerniereModif>
  <ScenarioCourant NomRef="Sc_M3-6I_c10"/>
  <Repertoires>
    <Repertoire Nom="CONFIG">
      <path>Config</path>
    </Repertoire>
    <Repertoire Nom="FICHETUDES">
      <path>.</path>
    </Repertoire>
    <Repertoire Nom="RAPPORTS">
      <path>Rapports</path>
    </Repertoire>
    <Repertoire Nom="RUNS">
      <path>Runs</path>
    </Repertoire>
  </Repertoires>
  <FichEtudes>
    <FichEtude Nom="M3-6I_c10.dclm.xml" Chemin=".\" Type="DCLM"/>
    <FichEtude Nom="M3-6I_c10.dcsp.xml" Chemin=".\" Type="DCSP"/>
    <FichEtude Nom="M3-6I_c10.dfrt.xml" Chemin=".\" Type="DFRT"/>
    <FichEtude Nom="M3-6I_c10.dlhy.xml" Chemin=".\" Type="DLHY"/>
    <FichEtude Nom="M3-6I_c10.dptg.xml" Chemin=".\" Type="DPTG"/>
    <FichEtude Nom="M3-6I_c10.dpti.xml" Chemin=".\" Type="DPTI"/>
    <FichEtude Nom="M3-6I_c10.dreg.xml" Chemin=".\" Type="DREG"/>
    <FichEtude Nom="M3-6I_c10.drso.xml" Chemin=".\" Type="DRSO"/>
    <FichEtude Nom="M3-6I_c10.ocal.xml" Chemin=".\" Type="OCAL"/>
    <FichEtude Nom="M3-6I_c10.optg.xml" Chemin=".\" Type="OPTG"/>
    <FichEtude Nom="M3-6I_c10.opti.xml" Chemin=".\" Type="OPTI"/>
    <FichEtude Nom="M3-6I_c10.optr.xml" Chemin=".\" Type="OPTR"/>
    <FichEtude Nom="M3-6I_c10.ores.xml" Chemin=".\" Type="ORES"/>
    <FichEtude Nom="M3-6I_c10.pcal.xml" Chemin=".\" Type="PCAL"/>
    <FichEtude Nom="M3-6I_c10.pnum.xml" Chemin=".\" Type="PNUM"/>
  </FichEtudes>
  <SousModeles>
    <SousModele Nom="Sm_M3-6I_c10">
      <Type>Crue10</Type>
      <IsActive>true</IsActive>
      <Commentaire>Sc_M3-6I_c9 converti en CRUE10&#xd;
Régimes permanents et transitoire. CLimM : Qapp(t), Zimp(t), Ouv(t) --&gt; incompatible avec c10m9</Commentaire>
      <AuteurCreation>gressier</AuteurCreation>
      <DateCreation>2017-06-23T09:06:13.869</DateCreation>
      <AuteurDerniereModif>DURON</AuteurDerniereModif>
      <DateDerniereModif>2023-04-21T15:37:17.465</DateDerniereModif>
      <SousModele-FichEtudes>
        <DRSO NomRef="M3-6I_c10.drso.xml"/>
        <DCSP NomRef="M3-6I_c10.dcsp.xml"/>
        <DPTG NomRef="M3-6I_c10.dptg.xml"/>
        <DFRT NomRef="M3-6I_c10.dfrt.xml"/>
      </SousModele-FichEtudes>
    </SousModele>
  </SousModeles>
  <Modeles>
    <Modele Nom="Mo_M3-6I_c10">
      <Type>Crue10</Type>
      <IsActive>true</IsActive>
      <Commentaire>Sc_M3-6I_c9 converti en CRUE10&#xd;
Régimes permanents et transitoire. CLimM : Qapp(t), Zimp(t), Ouv(t) --&gt; incompatible avec c10m9</Commentaire>
      <AuteurCreation>gressier</AuteurCreation>
      <DateCreation>2017-06-23T09:06:13.869</DateCreation>
      <AuteurDerniereModif>DURON</AuteurDerniereModif>
      <DateDerniereModif>2023-04-21T15:37:17.465</DateDerniereModif>
      <Modele-FichEtudes>
        <OPTR NomRef="M3-6I_c10.optr.xml"/>
        <OPTG NomRef="M3-6I_c10.optg.xml"/>
        <OPTI NomRef="M3-6I_c10.opti.xml"/>
        <PNUM NomRef="M3-6I_c10.pnum.xml"/>
        <DPTI NomRef="M3-6I_c10.dpti.xml"/>
        <DREG NomRef="M3-6I_c10.dreg.xml"/>
      </Modele-FichEtudes>
      <Modele-SousModeles>
        <Modele-SousModele NomRef="Sm_M3-6I_c10"/>
      </Modele-SousModeles>
    </Modele>
  </Modeles>
  <Scenarios>
    <Scenario Nom="Sc_M3-6I_c10">
      <Type>Crue10</Type>
      <IsActive>true</IsActive>
      <Commentaire>Régimes permanents et transitoire. CLimM : Qapp(t), Zimp(t), Ouv(t) --&gt; incompatible avec c10m9</Commentaire>
      <AuteurCreation>gressier</AuteurCreation>
      <DateCreation>2017-06-23T09:06:13.869</DateCreation>
      <AuteurDerniereModif>DURON</AuteurDerniereModif>
      <DateDerniereModif>2023-04-21T15:39:47.961</DateDerniereModif>
      <Scenario-FichEtudes>
        <OCAL NomRef="M3-6I_c10.ocal.xml"/>
        <ORES NomRef="M3-6I_c10.ores.xml"/>
        <PCAL NomRef="M3-6I_c10.pcal.xml"/>
        <DCLM NomRef="M3-6I_c10.dclm.xml"/>
        <DLHY NomRef="M3-6I_c10.dlhy.xml"/>
      </Scenario-FichEtudes>
      <Scenario-Modeles>
        <Scenario-Modele NomRef="Mo_M3-6I_c10"/>
      </Scenario-Modeles>
      <Runs>
        <Run Nom="R2023-04-21-15h39m47s">
          <Commentaire></Commentaire>
          <AuteurCreation>DURON</AuteurCreation>
          <DateCreation>2023-04-21T15:39:47.945</DateCreation>
          <AuteurDerniereModif>DURON</AuteurDerniereModif>
          <DateDerniereModif>2023-04-21T15:39:47.945</DateDerniereModif>
        </Run>
      </Runs>
      <RunCourant NomRef="R2023-04-21-15h39m47s"/>
    </Scenario>
  </Scenarios>
</ETU>

=== CNR-Engineering/Crue10_tools/crue10/data/templates/1.3/etu.xml
<?xml version="1.0" encoding="UTF-8"?>
<ETU xmlns="http://www.fudaa.fr/xsd/crue" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.fudaa.fr/xsd/crue http://www.fudaa.fr/xsd/crue/etu-1.3.xsd">
  <Commentaire>{{ metadata.Commentaire|html_escape }}</Commentaire>
  <AuteurCreation>{{ metadata.AuteurCreation }}</AuteurCreation>
  <DateCreation>{{ metadata.DateCreation }}</DateCreation>
  <AuteurDerniereModif>{{ metadata.AuteurDerniereModif }}</AuteurDerniereModif>
  <DateDerniereModif>{{ metadata.DateDerniereModif }}</DateDerniereModif>
  {%- if current_scenario_id %}
  <ScenarioCourant NomRef="{{ current_scenario_id }}"/>
  {%- endif %}
  <Repertoires>
    {%- for name, folder in folders %}
    <Repertoire Nom="{{ name }}">
      <path>{{ folder }}</path>
    </Repertoire>
    {%- endfor %}
  </Repertoires>
  <FichEtudes>
	{%- for filename, xml_type in files %}
    <FichEtude Nom="{{ filename }}" Chemin=".\" Type="{{ xml_type }}"/>
    {%- endfor %}
  </FichEtudes>
  <SousModeles>
    {%- for sous_modele in sous_modeles %}
    <SousModele Nom="{{ sous_modele.id }}">
      <Type>{{ sous_modele.metadata.Type }}</Type>
      <IsActive>{{ sous_modele.metadata.IsActive }}</IsActive>
      <Commentaire>{{ sous_modele.metadata.Commentaire|html_escape }}</Commentaire>
      <AuteurCreation>{{ sous_modele.metadata.AuteurCreation }}</AuteurCreation>
      <DateCreation>{{ sous_modele.metadata.DateCreation }}</DateCreation>
      <AuteurDerniereModif>{{ sous_modele.metadata.AuteurDerniereModif }}</AuteurDerniereModif>
      <DateDerniereModif>{{ sous_modele.metadata.DateDerniereModif }}</DateDerniereModif>
      <SousModele-FichEtudes>
        <DRSO NomRef="{{ sous_modele.file_basenames.drso }}"/>
        <DCSP NomRef="{{ sous_modele.file_basenames.dcsp }}"/>
        <DPTG NomRef="{{ sous_modele.file_basenames.dptg }}"/>
        <DFRT NomRef="{{ sous_modele.file_basenames.dfrt }}"/>
      </SousModele-FichEtudes>
    </SousModele>
	{%- endfor %}
  </SousModeles>
  <Modeles>
    {%- for modele in modeles %}
    <Modele Nom="{{ modele.id }}">
      <Type>{{ modele.metadata.Type }}</Type>
      <IsActive>{{ modele.metadata.IsActive }}</IsActive>
      <Commentaire>{{ modele.metadata.Commentaire|html_escape }}</Commentaire>
      <AuteurCreation>{{ modele.metadata.AuteurCreation }}</AuteurCreation>
      <DateCreation>{{ modele.metadata.DateCreation }}</DateCreation>
      <AuteurDerniereModif>{{ modele.metadata.AuteurDerniereModif }}</AuteurDerniereModif>
      <DateDerniereModif>{{ modele.metadata.DateDerniereModif }}</DateDerniereModif>
      <Modele-FichEtudes>
        <OPTR NomRef="{{ modele.file_basenames.optr }}"/>
        <OPTG NomRef="{{ modele.file_basenames.optg }}"/>
        <OPTI NomRef="{{ modele.file_basenames.opti }}"/>
        <PNUM NomRef="{{ modele.file_basenames.pnum }}"/>
        <DPTI NomRef="{{ modele.file_basenames.dpti }}"/>
        {%- if has_regul %}
        <DREG NomRef="{{ modele.file_basenames.dreg }}"/>
        {%- endif %}
      </Modele-FichEtudes>
      <Modele-SousModeles>
        {%- for sous_modele in modele.liste_sous_modeles %}
        <Modele-SousModele NomRef="{{ sous_modele.id }}"/>
        {%- endfor %}
      </Modele-SousModeles>
    </Modele>
	{%- endfor %}
  </Modeles>
  <Scenarios>
    {%- for scenario in scenarios %}
    <Scenario Nom="{{ scenario.id }}">
      <Type>{{ scenario.metadata.Type }}</Type>
      <IsActive>{{ scenario.metadata.IsActive }}</IsActive>
      <Commentaire>{{ scenario.metadata.Commentaire|html_escape }}</Commentaire>
      <AuteurCreation>{{ scenario.metadata.AuteurCreation }}</AuteurCreation>
      <DateCreation>{{ scenario.metadata.DateCreation }}</DateCreation>
      <AuteurDerniereModif>{{ scenario.metadata.AuteurDerniereModif }}</AuteurDerniereModif>
      <DateDerniereModif>{{ scenario.metadata.DateDerniereModif }}</DateDerniereModif>
      <Scenario-FichEtudes>
        <OCAL NomRef="{{ scenario.file_basenames.ocal }}"/>
        <ORES NomRef="{{ scenario.file_basenames.ores }}"/>
        <PCAL NomRef="{{ scenario.file_basenames.pcal }}"/>
        <DCLM NomRef="{{ scenario.file_basenames.dclm }}"/>
        <DLHY NomRef="{{ scenario.file_basenames.dlhy }}"/>
      </Scenario-FichEtudes>
      <Scenario-Modeles>
        <Scenario-Modele NomRef="{{ scenario.modele.id }}"/>
      </Scenario-Modeles>
      {%- if scenario.runs %}
      <Runs>
        {%- for run_id, run in scenario.runs.items() %}
        <Run Nom="{{ run_id }}">
          <Commentaire>{{ run.metadata.Commentaire|html_escape }}</Commentaire>
          <AuteurCreation>{{ run.metadata.AuteurCreation }}</AuteurCreation>
          <DateCreation>{{ run.metadata.DateCreation }}</DateCreation>
          <AuteurDerniereModif>{{ run.metadata.AuteurDerniereModif }}</AuteurDerniereModif>
          <DateDerniereModif>{{ run.metadata.DateDerniereModif }}</DateDerniereModif>
        </Run>
        {%- endfor %}
      </Runs>
      <RunCourant NomRef="{{ scenario.current_run_id }}"/>
      {%- endif %}
    </Scenario>
	{%- endfor %}
  </Scenarios>
</ETU>
